Ext.define("Test.model.AccountDetails", {
  extend: "Test.model.Base",
  fields: [
    "ClientId",
    "TenthDigit",
    "CustomerName1",
    "StructNumber",
    "StructNumberFraction",
    "PreDirectionalCode",
    "StreetName",
    "StreetType",
    "PostDirectionalCode",
    "SecondaryAddressType",
    "SecondaryAddressNumber",
    "AddressLine1",
    "AddressLine2",
    "City",
    "State",
    "Zip",
    "PrimaryPhoneNumber",
    "EmailAddress",
    "EBill",
    "PremiseToken",
    "MeterNumber",
    "ServiceCode",
    "UseClassCode",
    "Model",
    "ClientNumber",
    "PvaFlag",
    "PvaAccount",
    "RateCode",
    "ReturnVal",
    "ErrorMessage",
  ],
});
